# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.7"

services:

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "9005:9000"
    networks:
      - bridge
    environment:
      - TZ=Etc/UTC
    container_name: listmonk_app
    command: [sh, -c, "yes | ./listmonk --install --config config.toml && ./listmonk --config config.toml"]
    volumes:
      - ./config.toml:/listmonk/config.toml

networks:
  bridge:

